wundergraph/wundergraph

.changeset/silver-days-ring.md, .github/workflows/packages-ci.yaml, packages/nextjs/src/handlebar.template.ts, packages/nextjs/src/index.ts
=> feat: allow base url

pkg/apihandler/apihandler.go, pkg/apihandler/apihandler_test.go, pkg/node/fixtures/top products with query.golden, pkg/node/fixtures/top products without query.golden, pkg/node/node_test.go
=> feat(apihandler): automatically ignore unknown query params

packages/sdk/src/middleware/plugins/hooks.ts, pkg/apihandler/apihandler.go, pkg/bundler/bundler.go
=> fix(hooks): pass response correctly, pass input arg when available

examples/cross-api-joins/tsconfig.json, examples/postgres/tsconfig.json, examples/publish-install-api/tsconfig.json, examples/simple/tsconfig.json, packages/default-testapp/tsconfig.json, packages/mtls-testapp/tsconfig.json, packages/nextjs-testapp/.wundergraph/operations/PastLaunches.graphql, packages/nextjs-testapp/tsconfig.json, packages/sdk/src/codegen/templates/typescript/index.ts, packages/sdk/src/codegen/templates/typescript/jsonschema.template.ts, packages/sdk/src/codegen/templates/typescript/react.ts, packages/sdk/src/codegen/templates/typescript/web.client.ts, pkg/templates/assets/templates/application/tsconfig.json, pkg/templates/assets/templates/publish-api/tsconfig.json
=> fix(codegen): detect internal input correctly

.github/workflows/packages-ci.yaml, .github/workflows/packages-release.yaml, cli/commands/generate.go, cli/commands/up.go, package.json, packages/default-testapp/.wundergraph/wundergraph.config.ts, packages/default-testapp/.wundergraph/wundergraph.server.ts, packages/sdk/src/middleware/internal-client.ts, packages/sdk/src/middleware/server.ts, pkg/apihandler/apihandler.go, pkg/apihandler/apitransport.go, pkg/bundler/bundler.go, pkg/scriptrunner/scriptrunner.go
=> fix: restart hooks server, ensure __wg exists

pkg/apihandler/apihandler.go
=> fix: break request on hook error, improve logging

package.json
=> fix: #86 support pnpm 7.5+

docs-website/src/components/Fence.jsx
=> docs: fixed issue where code example would have double new lines

docs-website/src/styles/prism.css
=> docs: use proper colors in code boxes in light mode

docs-website/package-lock.json, docs-website/package.json, docs-website/src/components/Icon.jsx, docs-website/src/pages/index.md
=> docs: add new icons to overview

docs-website/src/components/Icon.jsx
=> docs: fix overview icons in darkmode

docs-website/src/components/Layout.jsx, docs-website/src/pages/_app.jsx
=> docs: added option to hide table of contents

docs-website/src/components/Layout.jsx
=> docs: align navigation links correctly on small screens

docs-website/markdoc/nodes.js, docs-website/src/components/Heading.jsx, docs-website/src/components/Hero.jsx, docs-website/src/components/Layout.jsx, docs-website/src/pages/_app.jsx
=> docs: make headings sharable

docs-website/src/components/Navigation.jsx, docs-website/src/utils/scroll-into-view.js
=> fix: scroll navigation links into view

docs-website/src/components/Layout.jsx
=> docs: add fullWidthContent frontmatter option

Makefile, pnpm-lock.yaml
This will fix a lot of conflicting issues, type issues on dev and build issues on CI. docs-website is a workspace so we should not use NPM to install packages.
=> chore: do not use NPM for docs as it is a pnpm workspace

docs-website/src/pages/manifesto.md
=> chore(docs-website): typos

docs-website/src/components/Layout.jsx
=> chore(docs-website): fix logo redirect to landing page

docs-website/src/pages/docs/use-cases/enabling-your-organization-to-become-api-first.md
=> chore(docs-website): edits and suggestion for api-first content page

docs-website/src/pages/docs/examples/hello-world.md
This pull request fixes a typo in the documentation of the hello world example.
=> chore(docs-website): fix typo in hello-world.md

docs-website/src/components/ThemeSelector.jsx
=> feat: change theme color to reflect the theme

packages/sdk/src/v2openapi/__snapshots__/index.test.ts.snap, packages/sdk/src/v2openapi/index.ts, packages/sdk/src/v2openapi/testdata/with_path_parameters.yaml
=> fix: issue with unhandled hyphens in input names

cli/commands/generate.go, cli/commands/up.go, pkg/bundler/bundler.go, pkg/scriptrunner/scriptrunner.go
=> fix(generate): exit with code 1 on error

pkg/graphiql/graphiql.html
=> feat: upgrade graphiql

cli/commands/add.go, cli/commands/generate.go, cli/commands/install-prisma-dependencies.go, cli/commands/publish.go, cli/commands/remove.go, cli/commands/root.go, cli/commands/start.go, cli/commands/up.go, pkg/datasources/database/engine.go, pkg/files/files.go
=> fix: unify .wundergraph directory resolution

packages/sdk/package.json, packages/sdk/src/middleware/server.ts, pnpm-lock.yaml
This PR will use a custom Pino instance as a base logger for the whole server. Pino is compatible with Fastify logger. There are no changes needed.
=> feat(server): introduce pino base logger

.github/workflows/engine-ci.yaml, CONTRIBUTING.md, packages/sdk/src/middleware/server.ts, pkg/s3uploadclient/s3uploadclient_test.go
=> fix(types): make webhooks optional

examples/auth0-oidc-authentication/package.json, examples/caching/package.json, examples/faunadb-nextjs/package.json, examples/inject-bearer/package.json
=> fix: examples, .env file loading

pkg/authentication/authentication.go
=> fix: improve hooks error handling

cli/commands/up.go, docs-website/src/pages/docs/features/type-script-webhooks-to-integrate-third-party-applications.md, examples/webhooks/.wundergraph/webhooks/github.ts, packages/default-testapp/.wundergraph/webhooks/github.ts, packages/default-testapp/.wundergraph/webhooks/stripe.ts, packages/sdk/src/index.ts, packages/sdk/src/webhooks/index.ts, packages/sdk/src/webhooks/types.ts, pkg/webhooks/webhooks.go
This PR improves the webhook types. It is now possible to add types for all request and response properties.
=> feat: improve webhook types

docs-website/src/pages/docs/directives-reference/inject-current-datetime-directive.md, docs-website/src/pages/docs/features/graphql-to-json-rpc-compiler.md, docs-website/src/pages/docs/guides/extend-json-fields-with-more-specific-types.md, docs-website/src/pages/docs/supported-data-sources/mysql.md, docs-website/src/pages/docs/supported-data-sources/postgresql.md, docs-website/src/pages/docs/supported-data-sources/rest-openapi.md, docs-website/src/pages/docs/supported-data-sources/sqlite.md
=> chore: fixed broken links on docs

pkg/bundler/bundler.go
=> fix: dont exit on bundle errors in dev

docs-website/src/pages/docs/wundergraph-server-ts-reference/webhooks.md
=> chore: last broken link fix

.github/actions/node/action.yaml, .github/workflows/engine-ci.yaml, .github/workflows/engine-release-preview.yaml, .github/workflows/engine-release.yaml, .github/workflows/packages-ci.yaml
Sepparated from: [151](https://github.com/wundergraph/wundergraph/pull/151/files)
=> chore: protoc, update version

examples/apollo-federation/package.json, examples/auth0-oidc-authentication/package.json, examples/caching/package.json, examples/cross-api-joins/package.json, examples/faunadb-nextjs/package.json, examples/fragments/package.json, examples/golang-client/package.json, examples/hooks/package.json, examples/inject-bearer/package.json, examples/keycloak-oidc-authentication/package.json, examples/migrate-from-apollo/package.json, examples/nextjs-postgres-prisma/package.json, examples/nextjs-postgres-user-filters/package.json, examples/nextjs/package.json, examples/postgres/package.json, examples/publish-install-api/package.json, examples/rbac/package.json, examples/simple/package.json, examples/webhooks/package.json
=> chore: examples, bump versions

packages/sdk/README.md, packages/sdk/src/client/index.ts, packages/sdk/src/internal/index.ts, packages/sdk/src/utils/hash.ts, packages/sdk/src/utils/helper.ts, packages/sdk/src/utils/serialize.test.ts, packages/sdk/src/utils/serialize.ts
The https://bundlephobia.com/package/object-hash@2.0.1 dependency is too heavy.
=> feat: custom stable hash function for js values

docs-website/src/pages/docs/wundergraph-server-ts-reference/configure-wundergraph-server-options.md
=> chore: fix wundergraph server options docs examples

packages/swr/src/hooks.ts
=> fix(swr): reset user cache after logout

packages/sdk/package.json, pnpm-lock.yaml
=> chore: update wunderctl

examples/nextjs-swr/.graphqlconfig, examples/nextjs-swr/.wundergraph/wundergraph.config.ts, examples/nextjs-swr/.wundergraph/wundergraph.server.ts, examples/nextjs-swr/lib/wundergraph.ts, examples/nextjs-swr/package.json, examples/nextjs-swr/pages/authentication.tsx, packages/sdk/src/client/types.ts, packages/sdk/src/codegen/templates/typescript/client.template.ts, packages/swr/src/hooks.ts
=> feat: add auth example for swr

cli/commands/root.go, cli/commands/up.go, cli/helpers/process.go, go.mod, go.sum, pkg/node/node.go
=> chore: fix signals handling for cli up

pkg/node/node.go
=> chore: update log msg

pkg/authentication/authentication.go
Currently token auth providers without a `userInfoEndpoint` will always result in an `undefined` user in the wundergraph context object.
=> fix(authentication): userInfoEndpoint should be optional for token auth providers

packages/sdk/package.json, pnpm-lock.yaml
=> chore: wunderctl, update

go.mod, go.sum
=> chore: update, graphql-go-tools

packages/sdk/package.json, packages/sdk/src/definition/federation-introspection.ts, packages/sdk/src/definition/graphql-introspection.ts, packages/sdk/src/definition/introspection-fetcher.ts, pnpm-lock.yaml
=> chore: add introspection fetcher with retries

docs-website/src/pages/docs/examples/nextjs-swr.md, packages/swr/README.md, packages/swr/src/index.ts, pnpm-lock.yaml, testapps/nextjs/package.json, testapps/nextjs/pages/swr.tsx
=> feat: re-export SWR to prevent context issues

docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-cors.md
=> docs: add cors wildcard example

pkg/datasources/database/engine.go
Left in https://github.com/wundergraph/wundergraph/pull/267/files
=> fix: remove accidentally left Println()

cli/commands/node.go, cli/commands/start.go, packages/sdk/src/middleware/server.ts, pkg/hooks/hooks.go, pkg/node/buildinfo.go, pkg/node/node.go
=> feat: healthcheck, node and hooks server

docs-website/config/navigation.js, docs-website/src/pages/docs/guides/debugging.md, docs/debugging.md
- docs(debugging): debugging for vsvode
- docs: add initial document with instructions for debugging
=> docs: initial docs page for debugging

pkg/httpidletimeout/httpidletimeout.go, pkg/httpidletimeout/httpidletimeout_test.go, pkg/httpidletimeout/options.go, pkg/node/node.go
- feat: add skipping support to HTTP idle timer middleware
- feat: make idle timer ignore healthcheck endpoint
=> feat: make idle timer ignore healtcheck endpoint

packages/sdk/src/definition/introspection-cache.ts
When calculating the cache key, try reading any string found as if it
was a file. If we succeed at reading it, add it to the hash. This
ensures any change to a referenced file is picked up when calculating
the key and all data is regenerated accordingly.
=> fix: make introspection cache keys change when referenced files change

pkg/hooks/hooks.go, pkg/node/buildinfo.go, pkg/node/node.go, pkg/node/nodetemplates/resources/index.html
=> fix: health check with retry client

pkg/apihandler/apihandler.go, pkg/apihandler/internalapihandler.go, pkg/authentication/authentication.go, testapps/default/.wundergraph/wundergraph.server.ts
This PR gracefully handles errors caused by canceled contexts when the client disconnects.
=> chore: improve error handling

cli/commands/generate.go, cli/commands/up.go, packages/sdk/src/definition/merge.ts, pkg/engineconfigloader/engineconfigloader.go
- fix: log message about hooks not found using logger
- fix: avoid crashing when there are no hooks definitions
- fix: crash if API is missing DataSources or Fields or Types or Schema
=> fix: errors when wundergraph.server.ts does not exist

.github/workflows/engine-ci.yaml, .github/workflows/engine-release-preview.yaml, .github/workflows/engine-release.yaml, .github/workflows/labeler.yaml, .github/workflows/packages-ci.yaml, .github/workflows/pr-title.yaml, .github/workflows/tag-engine-release.yaml, .github/workflows/wundernode-docker-release.yaml
=> chore: limit CI runs to 20 minutes

pkg/apihandler/apihandler.go, pkg/inputvariables/validator.go, pkg/inputvariables/validator_test.go, pkg/node/fixtures/top products with invalid query as wg variables.golden, pkg/node/fixtures/top products with invalid query.golden, pkg/node/fixtures/top products with query as wg variables.golden, pkg/node/node_test.go
This PR adds better error messages in case input validation fails. This gives useful information to the user of the API to send the correct inputs.
=> feat: add better error messages for input validation

docs-website/src/pages/docs/features/api-namespacing.md
Fix minor typo in documentation for word 'for'
=> docs: correct minor spelling typo

examples/apollo-federation/package.json, examples/auth0-oidc-authentication/package.json, examples/caching/package.json, examples/cross-api-joins/package.json, examples/faunadb-nextjs/package.json, examples/fragments/package.json, examples/golang-client/package.json, examples/graphql-apollo-subscriptions/package.json, examples/graphql-hasura-subscriptions/package.json, examples/graphql-sse-subscriptions/package.json, examples/graphql-subscriptions-hooks/package.json, examples/graphql-ws-subscriptions/package.json, examples/graphql-yoga-sse-subscriptions/package.json, examples/hooks/package.json, examples/inject-bearer/package.json, examples/keycloak-oidc-authentication/package.json, examples/migrate-from-apollo/package.json, examples/nextjs-postgres-prisma/package.json, examples/nextjs-postgres-user-filters/package.json, examples/nextjs-swr/package.json, examples/nextjs/package.json, examples/postgres/package.json, examples/publish-install-api/package.json, examples/rbac/package.json, examples/schema-extension/package.json, examples/simple/package.json, examples/vite-swr/package.json, examples/webhooks/package.json, packages/sdk/package.json, pnpm-lock.yaml
- chore: update wunderctl version in SDK dependency
- chore: bump dependency versions in examples
=> chore: bump versions for next release

docs/migrations/sdk-0.122.0-0.123.0.md
=> docs: add migration guide for SDK 0.123.0

packages/sdk/package.json, pnpm-lock.yaml
=> chore(release): bump wunderctl dependency in sdk to 0.118.1

packages/nextjs/src/template.ts, packages/sdk/src/codegen/templates/index.ts, packages/sdk/src/index.ts
=> fix: generate all required templates

examples/nextjs-postgres-prisma/package.json, examples/nextjs-postgres-prisma/tsconfig.json
=> fix: fix nextjs postgress example

packages/sdk/src/graphql/operations.ts
wunderctl up continues to run on a loop waiting for changes and
triggering code generation again when appropriate
Fixes ENG-797 too
=> fix: stop wunderctl on normalization errors, exit with non-zero

README.md, examples/openapi-mocking/.gitignore, examples/openapi-mocking/.wundergraph/.graphqlconfig, examples/openapi-mocking/.wundergraph/api.yaml, examples/openapi-mocking/.wundergraph/operations/NewNote.graphql, examples/openapi-mocking/.wundergraph/operations/NoteByID.graphql, examples/openapi-mocking/.wundergraph/wundergraph.config.ts, examples/openapi-mocking/.wundergraph/wundergraph.operations.ts, examples/openapi-mocking/.wundergraph/wundergraph.server.ts, examples/openapi-mocking/README.md, examples/openapi-mocking/package.json, examples/openapi-mocking/tsconfig.json
=> feat: add example for OpenAPI and mocking

docs-website/src/pages/docs/features/type-script-hooks-to-customize-the-api-gateway-middleware.md
=> docs: replace word 'you' with 'your'

examples/faunadb-nextjs/lib/wundergraph.ts, examples/faunadb-nextjs/package.json, examples/faunadb-nextjs/pages/index.tsx, examples/nextjs-swr/.wundergraph/wundergraph.config.ts
=> fix: fauna-db example

docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-graphqlconfig.md
=> chore(docs): remove app from graphqlconfig

docs-website/src/pages/docs/architecture/wundergraph-conventions.md
=> docs: fix env.from in conventions

go.mod, go.sum
=> fix: rest datasource post body arguments

packages/sdk/package.json, pnpm-lock.yaml
=> chore: increase wunderctl dep in SDK to 0.119.1

examples/simple/jest.config.js
=> fix: add missing jest config in simple example

examples/vite-swr/.graphqlconfig, examples/vite-swr/.wundergraph/wundergraph.config.ts, examples/vite-swr/src/lib/wundergraph.ts
=> fix: fix vite-swr example

.github/workflows/packages-ci.yaml, pkg/datasources/database/engine.go
Fixes ENG-511
Fixes ENG-740
Fixes ENG-929
=> fix: make prisma engine exit cleanly

cli/commands/root.go
=> fix: handle telemetry flag correctly

docs-website/src/pages/docs/features/file-uploads-to-s3-compatible-file-storages.md, packages/sdk/src/client/client.ts, pkg/apihandler/apihandler.go, pkg/authentication/authentication.go
Will add example after merge as a separate PR
=> fix: csrf and authenticated uploads

examples/nextjs-file-upload/.gitignore, examples/nextjs-file-upload/package.json
=> chore: update scripts for upload example

packages/sdk/package.json, pnpm-lock.yaml
=> chore: bump wunderctl dependency to >= 0.121

README.md, examples/nodejs-ts-client/.gitignore, examples/nodejs-ts-client/.wundergraph/.graphqlconfig, examples/nodejs-ts-client/.wundergraph/operations/Continents.graphql, examples/nodejs-ts-client/.wundergraph/operations/Countries.graphql, examples/nodejs-ts-client/.wundergraph/operations/Hello.graphql, examples/nodejs-ts-client/.wundergraph/wundergraph.config.ts, examples/nodejs-ts-client/.wundergraph/wundergraph.operations.ts, examples/nodejs-ts-client/.wundergraph/wundergraph.server.ts, examples/nodejs-ts-client/README.md, examples/nodejs-ts-client/client.ts, examples/nodejs-ts-client/jest.config.js, examples/nodejs-ts-client/package.json, examples/nodejs-ts-client/test/index.test.ts, examples/nodejs-ts-client/tsconfig.json
=> feat: add Node.js + TypeScript client example

pnpm-lock.yaml
=> fix: update outdated pnpm lockfile

packages/create-wundergraph-app/package.json, pnpm-lock.yaml
=> fix(create): move dotenv from devDependencies to dependencies

examples/apollo-federation/package.json
=> fix: apollo generate cmd name for examples CI

README.md
=> fix: minor typo in readme.md

pkg/httpidletimeout/httpidletimeout_test.go
- Counter used for testing was not atomic
- Wait interval was too tight, causing intermittent failures, widen it
=> fix: data race and variability in httpidletimeout test

docs-website/src/pages/getting-started.md
=> fix: Small typo

go.mod, go.sum, pkg/node/node_test.go
=> chore: update graphql-go-tools version

go.mod, go.sum
=> fix: sse subscription abort

go.mod, go.sum
=> feat: disable graphql maximum subscription message size limit

packages/sdk/package.json, pnpm-lock.yaml
=> chore: update wunderctl version

packages/sdk/package.json, pnpm-lock.yaml
=> chore: update wunderctl SDK dependency

examples/simple/.wundergraph/operations/Countries.graphql, examples/simple/.wundergraph/operations/Country.graphql, examples/simple/README.md, examples/simple/test/index.test.ts
=> fix: examples, simple

README.md, packages/sdk/README.md
=> chore: improve readmes

docs-website/src/pages/docs/directives-reference/remove-null-variables-directive.md, go.mod, go.sum
=> chore: engine, update version

docs-website/config/navigation.js, docs-website/src/pages/docs/guides/end-to-end-testing.md, docs-website/src/pages/docs/guides/integration-testing.md
=> docs: add end to end testing guide

packages/sdk/src/operations/operations.ts
=> fix: factory type errors

packages/sdk/package.json, pnpm-lock.yaml
=> chore: update wunderctl dependency to 0.129

examples/golang-client/.wundergraph/operations/Countries.graphql, examples/nodejs-ts-client/.wundergraph/operations/Countries.graphql
The issue is with the origin. We use these examples as templates, this fix makes them stable.
=> chore: examples, fix issues with origin

packages/sdk/src/configure/index.ts
=> fix: pass file upload hooks to upload configuration resolution

docs-website/src/pages/docs/cloud/deployments.md
=> chore: docs, cloud deployment

packages/sdk/package.json, pnpm-lock.yaml
=> chore: bump wunderctl SDK dependency to 0.130

examples/schema-extension/.wundergraph/wundergraph.config.ts, packages/sdk/src/configure/operations.ts
=> chore: examples, clean up

docs-website/config/navigation.tsx, docs-website/src/components/Icon.jsx, docs-website/src/pages/docs/auth/auth0/index.md, docs-website/src/pages/docs/auth/github/index.md, docs-website/src/pages/docs/auth/index.md, docs-website/src/pages/docs/auth/keycloak/index.md, docs-website/src/pages/docs/auth/openid-connect/index.md, docs-website/src/pages/docs/features/openid-connect-based-authentication.md
=> chore: add auth docs

docs-website/src/pages/docs/examples/graphql-apollo-subscriptions.md
=> fix: link in graphql-apollo-subscriptions.md

go.mod, go.sum, pkg/node/node_test.go
=> chore: update graphql-go-tools

docs-website/src/pages/index.jsx
=> fix: quickstart links

docs-website/src/pages/docs/getting-started/nextjs-quickstart.md, docs-website/src/pages/docs/getting-started/remix-quickstart.md, docs-website/src/pages/docs/getting-started/vite-quickstart.md
=> chore: change typo countries -> spaceX

docs-website/next.config.js
=> docs: add redirect from old "getting started" to new one

docs/wundergraphVSpostgraphile.md
This PR is for the issue [docs] Comparison to PostGraphile #215, i have made the doc and added it to a folder as discussed with
@Slickstef11 
By making a contribution to this project, I certify that:
* (a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
* (b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or
* (c) The contribution was provided directly to me by some …
=> chore(docs): added the comparison of Wundergraph and Postgraphile (#670)Co-authored-by: Dustin Deus <deusdustin@gmail.com>

docs-website/config/navigation.tsx, docs-website/src/pages/docs/clients-reference/index.md
=> docs: add solid link

.github/workflows/engine-ci-skip.yaml, .github/workflows/engine-ci.yaml, .github/workflows/packages-ci-skip.yaml, .github/workflows/packages-ci.yaml
Adding skip actions to allow required checks to pass on the ignored paths
Done according to:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
=> chore: ignore docs path explicitly

docs-website/src/pages/docs/getting-started/quickstart.md
The current link leads to a 404 as the [simple example](https://github.com/wundergraph/wundergraph/tree/main/examples/simple/.wundergraph/operations) now has a new operation `/Country` - as opposed to `/Countries` earlier.
=> fix: updating quickstart guide with new link

docs-website/src/components/Navigation.jsx
=> chore: fix all docs flickering

.github/workflows/engine-ci-skip.yaml
=> chore: fix engine-ci-skip

packages/create-wundergraph-app/src/helpers/getRepository.ts
=> fix: support yarn 3 with create-wundergraph-app --init

docs-website/config/navigation.tsx, docs-website/src/pages/docs/cloud/custom-domains.md, docs-website/src/pages/docs/cloud/index.md
=> chore: add custom domains documentation (#707)Co-authored-by: David Stutt <david@wundergraph.com>

docs-website/src/pages/docs/cloud/custom-domains.md
=> chore: added google to custom domain docs

docs-website/src/pages/docs/cloud/custom-domains.md
=> chore: add GoDaddy to custom domain docs

packages/sdk/package.json, pnpm-lock.yaml
=> chore: increase wunderctl dependency version to 0.132 in SDK

packages/sdk/package.json, pnpm-lock.yaml
=> chore: update the wunderctl version

docs-website/src/pages/docs/examples/nextjs-postgresql-prisma.md
Fix wrong example name causing error "The given example name doesnt exist in the Wundergraph repository"
=> docs: fix wrong example name (#735

README.md, docs-website/config/navigation.tsx, docs-website/src/pages/docs/cloud/configuration.md, docs-website/src/pages/docs/cloud/index.md
Demo: https://github.com/wundergraph/cloud-multi-projects-demo
=> docs: document multi workspace support

go.mod, go.sum
=> chore: bump graphql-go-tools to 1.62.1

packages/sdk/package.json, pnpm-lock.yaml
=> chore: bump wunderctl dependency to 0.134

docs-website/config/navigation.tsx, docs-website/src/pages/docs/cloud/integrations/neon.md
=> feat: add docs for neon integration

lerna.json
Otherwise it won't get picked up for releases
=> chore: add @wundergraph/svelte-query to lerna config

packages/sdk/package.json, pnpm-lock.yaml
=> chore: bump to 138.0

examples/apollo-federation/package.json, examples/auth0-oidc-authentication/package.json, examples/caching/package.json, examples/faunadb-nextjs/package.json, examples/inject-bearer/package.json, examples/keycloak-oidc-authentication/package.json, examples/learn-wundergraph/package.json, examples/migrate-from-apollo/package.json, examples/nextjs-clerk/package.json, examples/nextjs-file-upload/package.json, examples/nextjs-postgres-prisma/package.json, examples/nextjs-postgres-user-filters/package.json, examples/nextjs-react-query/package.json, examples/nextjs-todos/package.json, examples/nextjs-typescript-functions/package.json, examples/nextjs/package.json, examples/rbac/package.json
=> chore: update versions

pkg/authentication/github.go, pkg/authentication/oidc.go
Change OIDC and GitHub cookie state problems to log warnings rather than errors.
=> chore: change error to warn

docs-website/src/pages/docs/cloud/errors.md
=> chore: add newline to errors.md

docs-website/src/pages/docs/getting-started/quickstart.md
Update the quickstart docs to match with the generated repo.
=> docs: update quickstart.md

examples/sveltekit/.wundergraph/tsconfig.json, examples/sveltekit/.wundergraph/wundergraph.config.ts, examples/sveltekit/src/routes/+layout.ts, examples/sveltekit/src/routes/styles.css, examples/sveltekit/svelte.config.js, examples/sveltekit/vite.config.ts, examples/vite-svelte/.wundergraph/wundergraph.config.ts, examples/vite-svelte/index.html, examples/vite-svelte/src/app.css, examples/vite-svelte/src/main.ts, examples/vite-svelte/svelte.config.js, examples/vite-svelte/vite.config.ts
This PR fixes the files that were not previously formatted with prettier.
=> fix: formatting errors introduced in svelte examples

packages/sdk/package.json, pnpm-lock.yaml
=> chore: update wunderctl dependency

examples/apollo-federation/package.json, examples/auth0-oidc-authentication/package.json, examples/caching/package.json, examples/faunadb-nextjs/package.json, examples/inject-bearer/package.json, examples/keycloak-oidc-authentication/package.json, examples/learn-wundergraph/package.json, examples/migrate-from-apollo/package.json, examples/nextjs-clerk/package.json, examples/nextjs-file-upload/package.json, examples/nextjs-postgres-prisma/package.json, examples/nextjs-postgres-user-filters/package.json, examples/nextjs-react-query/package.json, examples/nextjs-todos/package.json, examples/nextjs-typescript-functions/package.json, examples/nextjs/package.json, examples/postgres/package.json, examples/rbac/package.json, testapps/nextauth/package.json, testapps/nextjs/package.json, testapps/vite/package.json
=> fix: run examples in log mode for multi process examples

cli/commands/up.go
=> fix: avoid logging in tui mode

packages/sdk/package.json, pnpm-lock.yaml
=> chore: update wunderctl dependency to 0.141.0

README.md
Add two shields to the README and NPM landing page:
GitHub Stars shield
Discourse shield
=> chore: add GitHub star and Discourse shields to NPM landing page

README.md, packages/sdk/README.md
Apply the shield changes to the sdk README
=> chore: apply shield changes to sdk readme

packages/sdk/package.json, pnpm-lock.yaml
=> chore: bump wunderctl to 0.142

examples/vite-react-relay/.babelrc
Formats `.babelrc` file in examples
=> fix: format .babelrc file

packages/react-relay/README.md, packages/sdk/README.md
Creating this PR to update the examples used in create-wundergraph-app
=> docs: add discourse to the SDK readme

packages/react-relay/package.json, pnpm-lock.yaml
Moves relay & wundergraph sdk to peer dependencies of Relay package to prevent issues with build
=> fix: move wundergraph & relay to peer deps of relay package

examples/nextjs-relay/package.json, examples/vite-react-relay/package.json
The start commands of relay examples are not consistently working due to race condition between `wunderctl up` & `relay compiler`
This PR will make the `wunderctl generate` before the other commands to ensure consistency
=> fix: relay examples start commands

packages/protobuf/wgpb/wundernode_config.ts
=> chore: random change to trigger format check

packages/sdk/package.json, pnpm-lock.yaml
=> chore: update wunderctl dependency to 0.143.0

packages/sdk/src/operations/operations.ts, packages/testsuite/apps/basic/.wundergraph/operations/functions/simple.ts, testapps/simple/.wundergraph/operations/users/getWeather.ts, testapps/simple/.wundergraph/operations/users/simple.ts
=> fix: ensure input is undefined when not defined as schema

.github/workflows/engine-release.yaml, .github/workflows/packages-release.yaml, packages/testsuite/package.json
See https://github.blog/2023-04-19-introducing-npm-package-provenance/
This should work out of the box with [pnpm](https://github.com/nuxt/nuxt/commit/ec1503731b1cabb331c28726bba3fb4d4e2d3af8) for wunderctl but it's unclear if lerna is supported although all are using [libnpmpublish](https://github.com/npm/cli/blob/c7f4b35cc08aca754011778b1da149bc0c4c6494/workspaces/libnpmpublish/lib/provenance.js#L5) under the hood.
=> feat: test package provenance

.npmrc
=> chore: enable dedupe peers

package.json, packages/react-query/package.json, packages/solid-query/package.json, packages/svelte-query/package.json, packages/vue-query/package.json, pnpm-lock.yaml
Updates all tanstack query packages and override query-core version to make sure all packages use the same version to prevent type errors.
=> fix: update tanstack query

.npmrc
=> chore: undo dedupe peer deps

pkg/apihandler/apihandler.go, pkg/apihandler/internalapihandler.go
Fixes planning errors of the GraphQL handler. Can be tested with a load test.
=> fix: graphQL handler planning errors

packages/sdk/package.json, pnpm-lock.yaml
=> chore: bump wunderctl dependency to 0.146.1

docs-website/src/pages/docs/databases/prisma.md
=> chore: fix typo in Prisma docs

packages/create-wundergraph-app/src/index.ts
Makes debugging problems easier
=> fix: print error reason when create-wundergraph-app fails

pkg/logging/logging.go
We need access to these 2 variables for application logs on the cloud.
=> feat: add projectID and environmentID to logs

packages/sdk/src/testing/mock-server.ts
=> feat: support all HTTP methods in mocking library

LICENSE
Changed WG UG -> WG Inc.; updated copyright year
=> chore(docs-license): update company info

packages/sdk/package.json, pnpm-lock.yaml
=> chore: update wunderctl dependency to 0.150.0

docs-website/src/pages/docs/guides/context-factory.md
=> docs: fix typo and minor edits in context factory guide

.github/workflows/examples-ci.yaml
Use checkout@v3 instead of checkout@v2
=> fix: deprecation warning in Examples CI

packages/sdk/package.json, pnpm-lock.yaml
=> chore: update wunderctl dependency to 0.152.0

packages/orm/package.json
=> chore: add version to orm

packages/orm/package.json
=> chore: version orm

packages/orm/package.json, pnpm-lock.yaml
=> fix: add hotscript and type fest to deps

docs-website/config/navigation.tsx, docs-website/src/components/Navigation.jsx, docs-website/src/pages/docs/examples/index.md, docs-website/src/pages/docs/examples/orm.md, docs-website/src/pages/docs/typescript-orm-reference/index.md, examples/orm/.gitignore, examples/orm/.graphqlrc.yaml, examples/orm/.wundergraph/operations/country.ts, examples/orm/.wundergraph/wundergraph.config.ts, examples/orm/.wundergraph/wundergraph.operations.ts, examples/orm/.wundergraph/wundergraph.server.ts, examples/orm/README.md, examples/orm/jest.config.js, examples/orm/package.json, examples/orm/test/index.test.ts, examples/orm/tsconfig.json
=> chore: add ts orm reference and orm example

docs-website/src/pages/docs/features/authorization-role-based-access-control-rbac.md
=> docs: Use correct hook in Authorization - Role Based Access Control

docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-wundernode-options.md, docs-website/src/pages/docs/wundergraph-server-ts-reference/configure-wundergraph-server-options.md
=> chore(docs): improve docs about env

packages/orm/docs/architecture.md
Fixes small typo in `packages/orm/docs/architecture.md`.
=> chore: fix typo in orm architecture.md

docs-website/config/navigation.tsx, docs-website/src/pages/docs/cloud/configuration.md, docs-website/src/pages/docs/cloud/deployments.md, docs-website/src/pages/docs/cloud/integrations/vercel.md, docs-website/src/pages/docs/cloud/redeployment.md
=> chore: add redeployment docs; build script prioritisation

docs-website/src/pages/docs/self-hosted/docker.md
=> chore: use docker example as source of truth

packages/sdk/package.json, pnpm-lock.yaml
=> chore: update wunderctl dependency to 0.153.0

packages/sdk/package.json, pnpm-lock.yaml
=> chore: bump wunderctl dependency in SDK to 0.154.0

packages/nextjs/src/template.ts
=> fix: missing ts generator in nextjs package

docs-website/src/pages/docs/guides/extend-json-fields-with-more-specific-types.md, docs-website/src/pages/docs/wundergraph-config-ts-reference/schema-extension-configuration.md
=> chore: update extend json fields docs

pkg/node/config.go
Do not panic if otel variables are missing
=> chore: fix otel variable panics

packages/sdk/src/server/plugins/telemetry.test.ts, packages/sdk/src/server/plugins/telemetry.ts, pkg/apihandler/apitransport.go, pkg/hooks/hooks.go, pkg/trace/transport.go, pkg/trace/transport_test.go, pkg/trace/wrap_handler.go, pkg/trace/wrap_handler_test.go, pkg/webhookhandler/webhookhandler.go
This PR aligns several OTEL attributes. Previously, we added client attributes in a server context.
=> fix: align otel attributes

packages/sdk/package.json, pnpm-lock.yaml
=> chore: update wunderctl dependency to 0.158.0

lerna.json
=> chore: add orm to lerna

packages/orm/README.md, packages/orm/src/orm.ts
=> fix: bump orm version

docs-website/src/pages/docs/cloud/otel-collector.md
=> chore(otel): update otel docs

packages/sdk/package.json, pnpm-lock.yaml
=> chore: bump wunderctl dependency in SDK to 0.159.0

pkg/apihandler/apihandler_test.go
=> chore: fix data race in test

docs-website/src/pages/docs/cloud/deployments.md, docs-website/src/pages/docs/cloud/index.md
=> feat: announce cloud GA

.github/ISSUE_TEMPLATE/issue.yml
Clarify how to gather version and environment information
=> fix(issue): clarify how to gather versions

packages/sdk/src/openapibuilder/index.test.ts, packages/sdk/src/openapibuilder/index.ts
Previously we were just detecting if two types with the same name were
different and failing in that case, under the assumption that the user
could always renamed the types. Unfortunately, this turned out to not be
possible when the types are generated by some upstream APIs.
To support this use case, rename the new type by appending a number and
rename also all its references (within the schema component and its children).
This way the names won't collide anymore.
=> feat: support different types with the same when generating OAS

.github/goreleaser/.goreleaser-darwin.yml, .github/goreleaser/.goreleaser-linux.yml, .github/goreleaser/.goreleaser-windows.yml
archives/replacements has been removed, used name_template instead
=> fix: update goreleaser configuration for 1.19

.github/goreleaser/.goreleaser-darwin.yml, .github/goreleaser/.goreleaser-linux.yml, .github/goreleaser/.goreleaser-windows.yml
.Version field was missing when updating the name_template format
=> fix: goreleaser binary name templates

packages/sdk/package.json, pnpm-lock.yaml
=> chore: increase wunderctl dependency version in SDK to 0.163.0

cli/commands/root.go
Otherwise, running wunderctl up on an empty project might cause an
error and exit immediately. This also makes the metrics slightly more
accurate since we now always wait for the config to be generated
before we gather them.
=> fix: make telemetry metric generation async

pkg/datasources/database/fetch_engine.go, pkg/datasources/database/fetch_engine_test.go
We were accidentally downloading linux/amd64
=> fix: download correct prisma binaries for linux/arm64

docs-website/next.config.mjs, docs-website/src/pages/index.jsx
=> fix: broken link

packages/sdk/package.json, pnpm-lock.yaml
=> chore: bump wunderctl dependency in SDK to 0.164.0

docs-website/config/navigation.tsx, docs-website/src/pages/docs/openai/index.md, packages/sdk/src/openai/index.ts, testapps/default/.wundergraph/operations/openai/summarize_url_content.ts
Improve input validation for OpenAI, add docs.
With this release, we're adding more advanced input validation for the WunderGraph OpenAI integration to detect prompt injection attacks. We're also adding docs on how to get started with the integration.
=> feat: improve openai

pkg/operations/operations.go
=> fix: don't try to import server.ts if it doesn't exist, avoid importing it twice

lerna.json
Otherwise it's not picked up for releases
Fixes #1115
=> fix: add packages/vue-query to lerna

scripts/bump-wunderctl-in-sdk.sh
Increasing them by hand was getting annoying
=> chore: add script for bumping wunderctl dependency version

pkg/datasources/database/engine.go, pkg/datasources/database/fetch_engine.go, pkg/datasources/database/fetch_engine_test.go
- Detect LibreSSL correctly
- When the openssl command is not present, fallback to checking the
libraries on the fs, this way we don't have to hardcode alpine
Fixes #1104
=> fix: prisma openssl detection on alpine and fedora based distros

.github/workflows/engine-release.yaml
=> chore: add missing environment variable to goreleaser

docs-website/src/pages/docs/wundergraph-config-ts-reference/configure-authorization.md
=> chore: fix link

packages/sdk/package.json, pnpm-lock.yaml
=> chore: update wunderctl dependency to 0.169.0

pkg/apihandler/apihandler.go, pkg/authentication/oidc.go
=> fix: oidc token exchange

README.md, packages/sdk/package.json, pnpm-lock.yaml
=> chore: update wunderctl dependency to 0.169.1

docs-website/config/navigation.tsx, docs-website/src/pages/docs/cloud/wundergraph-ignore.md, pnpm-lock.yaml
=> feat: add docs about .wundergraphignore

packages/sdk/README.md
=> chore: remove discourse link

go.mod, go.sum, pkg/datasources/database/datasource_test.go
=> fix: remove duplicated @removeNullVariables directive

docs-website/src/pages/docs/examples/nextjs.md
This change fixes a typo in the nextjs example documentation.
=> chore: fix typo in nextjs examples doc

packages/sdk/src/server/plugins/functions.ts
For functions without any parameters it should be an empty object, to
match the types we have previously defined and simplify argument checks.
=> fix: make sure a function's input is always non null

packages/sdk/src/server/server.ts, pkg/authentication/oauth2.go
If HTTPS is forced, redirect to HTTPS. Otherwise use a protocol relative
redirect.
Fixes #1006
=> fix: don't force redirect to HTTP when redirecting to HTTPS is not forced

.golangci.yml, pkg/apihandler/apihandler_test.go, pkg/cacheheaders/cacheheaders_test.go, pkg/datasources/database/engine.go, pkg/datasources/database/fetch_engine_test.go, pkg/hooks/hooks.go, pkg/node/node_test.go, pkg/trace/transport_test.go
Fix the last remaining occurrences (mostly found in tests)
=> ci: add linter to detect unclosed http.Response bodies

docs-website/package-lock.json, docs-website/package.json
=> chore: lock version to fix type issue on docs website

packages/create-wundergraph-app/src/helpers/download.ts, packages/create-wundergraph-app/src/tests/index.test.ts, packages/testsuite/apps/nats-kv/nats-kv.test.ts, pkg/authentication/authentication.go, pkg/hooks/hooks.go
Previous timeout is too low for CI, avoid 2 downloads on the same test
which makes it run for too long
=> chore: split create-wg-app tests, increase timeout

packages/testsuite/apps/nats-kv/nats-kv.test.ts
This is constantly blocking PRs, disabling the tests for now until they are properly fixed.
=> chore: disable nats 2 tests

packages/sdk/package.json, packages/sdk/src/server/operations-client.ts, packages/sdk/src/server/server.ts, packages/sdk/src/server/types.ts, packages/sdk/test-d/operations-client.test-d.ts, packages/sdk/test-d/operations.test-d.ts, packages/sdk/test-d/server.test-d.ts, packages/sdk/test-d/webhook-factory.test-d.ts, pnpm-lock.yaml
=> fix: test-d tests in sdk

scripts/bump-sdk-in-examples.sh, scripts/bump-versions.sh
- Add arguments to automatically create a branch, commit and PR
- Rename script to bump-sdk-in-examples.sh
=> chore: improve script for bumping SDK in examples

cli/commands/root.go, cli/commands/up.go, examples/apollo-federation/package.json, examples/auth0-oidc-authentication/package.json, examples/caching/package.json, examples/faunadb-nextjs/package.json, examples/inject-bearer/package.json, examples/keycloak-oidc-authentication/package.json, examples/learn-wundergraph/package.json, examples/migrate-from-apollo/package.json, examples/nextjs-clerk/package.json, examples/nextjs-file-upload/package.json, examples/nextjs-postgres-prisma/package.json, examples/nextjs-postgres-user-filters/package.json, examples/nextjs-react-query/package.json, examples/nextjs-todos/package.json, examples/nextjs-typescript-functions/package.json, examples/nextjs/package.json, examples/open-telemetry/package.json, examples/rbac/package.json, testapps/nextauth/package.json, testapps/nextjs-integrations/package.json, testapps/nextjs/package.json, testapps/vite/package.json
TUI is still available and can be enabled with --ui
=> feat: enable log output by default

cli/commands/node.go, cli/commands/start.go, cli/commands/up.go, pkg/apihandler/apihandler.go, pkg/apihandler/apihandler_test.go, pkg/node/node.go, pkg/node/node_test.go
This allows debugging problems with requests that don't involve
operations (e.g. authentication)
=> feat: make --debug log all requests and responses to the node

packages/sdk/src/server/plugins/fetch.ts, packages/sdk/src/server/plugins/omnigraphOAS.ts, packages/sdk/src/server/plugins/omnigraphSOAP.ts
Log the method, headers, status codes and contents. These requests are unlikely
to carry binary data, so logging the payloads should not interfere with the terminal
output.
Requests and responses are logged at the debug level, while errors while calling
the underlying fetch are logged at warn error and rethrown.
=> feat: log requests and responses to OpenAPI and SOAP upstreams

pkg/telemetry/client.go, pkg/telemetry/client_test.go
If the server replied with an error, the response was assumed to be
correct.
=> fix: report errors when sending usage telemetry

packages/sdk/src/definition/index.ts
=> docs: add comment about introspect.OpenApi being phased out

docs-website/src/pages/docs/guides/bundle-generated-client-for-distribution.md, examples/nextjs-file-upload/package.json, package.json, packages/sdk/package.json, packages/testsuite/package.json, pnpm-lock.yaml, testapps/default/package.json, testapps/nextjs-integrations/package.json, testapps/nextjs-relay/package.json, testapps/nextjs/package.json
=> fix: updated zod to 3.22.3

packages/sdk/package.json, pnpm-lock.yaml
=> chore: bump wunderctl dependency in SDK to 0.178.1

packages/sdk/package.json, packages/sdk/src/server/plugins/omnigraphOAS.ts, packages/testsuite/apps/openapi/.wundergraph/api.yaml, packages/testsuite/apps/openapi/.wundergraph/operations/Bigint.graphql, packages/testsuite/apps/openapi/openapi.test.ts, packages/testsuite/apps/openapi/test-server.ts, pnpm-lock.yaml
=> fix: fixed issue where int64 in open api specs would fail to parse

package.json, packages/sdk/package.json, packages/sdk/patches/json-machete+0.95.6.patch, packages/sdk/patches/json-machete@0.94.5.patch, patches/json-machete@0.94.5.patch, pnpm-lock.yaml
=> fix: patch json-machete to propagate required from root objects to subobjects

packages/sdk/package.json, packages/sdk/src/server/plugins/fetch.ts, pnpm-lock.yaml
=> fix: fixed issue where open api mutation would cause gateway timeout after redirect

pkg/node/node.go
Streaming responses might never finish, causing the request to never
be answered
Fixes #1317
=> fix: don't intercept streaming responses for response logging

packages/sdk/package.json, pnpm-lock.yaml
=> fix: update to wunderctl 0.176.1

packages/sdk/package.json, pnpm-lock.yaml
=> fix: update wunderctl to 0.176.2

package.json, packages/sdk/src/testing/test-server.test.ts, packages/sdk/src/testing/test-server.ts, packages/sdk/src/testing/test-servers.ts, pnpm-lock.yaml, testapps/default/package.json, testapps/default/test/index.test.ts, testapps/default/vitest.config.ts
=> fix: make test server start timeout configurable

docs-website/src/pages/docs/auto-generated-operations-reference/index.md
=> chore: fix typo in code generation docs

packages/sdk/package.json, pnpm-lock.yaml
=> fix: update to wunderctl 0.176.3

packages/sdk/src/testing/test-server.ts
=> fix: test server timeout

docs-website/src/pages/docs/supported-frontend-frameworks/vite-js.md
=> docs: Fixes reference typo

packages/sdk/src/codegen/templates/typescript/client.template.ts
=> feat: add withheaders method to client

packages/rust-client/index.ts
=> feat: add derive Clone to rust client types

packages/sdk/package.json, pnpm-lock.yaml
=> chore: update wunderctl dependency to 0.177.0

package.json, packages/sdk/package.json, pnpm-lock.yaml
=> chore: update wunderctl dependency to 0.178.0

packages/sdk/package.json, pnpm-lock.yaml
=> chore: update wunderctl dependency to 0.179.0

packages/rust-client/index.ts, pnpm-lock.yaml, testapps/rust/.gitignore, testapps/rust/.wundergraph/oas.yaml, testapps/rust/.wundergraph/operations/OasTest.graphql, testapps/rust/.wundergraph/wundergraph.config.ts, testapps/rust/.wundergraph/wundergraph.generate.ts, testapps/rust/.wundergraph/wundergraph.operations.ts, testapps/rust/.wundergraph/wundergraph.server.ts, testapps/rust/package.json, testapps/rust/tsconfig.json
=> fix: recursive oas references in rust client generation

packages/sdk/package.json, pnpm-lock.yaml
=> chore: update wunderctl dependency to 0.179.1

packages/rust-client/index.ts
=> feat: add Clone trait to Rust Client

packages/sdk/package.json, pnpm-lock.yaml
=> chore: update wunderctl dependency to 0.180.0
