wundergraph/wundergraph

packages/wunderctl/src/cli.ts

Wunderctl can not be terminated by ctrl+c on Windows.

fix(wunderctl): terminated problem on Windows

---

cli/commands/start.go
cli/commands/up.go

fix: trigger server reload after initial config build

---

packages/sdk/src/v2openapi/index.ts

fix issue when current[0] is undefined
example:
C:\Working\_wundergraphTest\node_modules\@wundergraph\sdk\dist\v2openapi\index.js:1002
return prev + current[0].toUpperCase() + current.substring(1);
^
TypeError: Cannot read properties of undefined (reading 'toUpperCase')
at C:\Working\_wundergraphTest\node_modules\@wundergraph\sdk\dist\v2openapi\index.js:1002:38
at Array.reduce (<anonymous>)
at RESTApiBuilder.resolveArgumentName (C:\Working\_wundergraphTest\node_modules\@wundergraph\sdk\dist\v2openapi\index.js:997:47)
at RESTApiBuilder.traversePath (C:\Working\_wundergraphTest\node_modules\@wundergraph\sdk\dist\v2openapi\index.js:225:43)
at C:\Working\_wundergraphTest\node_modules\@wundergraph\sdk\dist\v2openapi\index.js:47:26
at Array.forEach (<anonymous>)
at RESTApiBuilder.build …

fix: openapi introspection defect

---

packages/default-testapp/.wundergraph/wundergraph.config.ts
packages/sdk/src/definition/index.ts

This PR improves error messages when running `wunderctl up`.
Originally, we've just thrown an Error / Rejected Promise, which results in a very verbose error message where it's hard to find the real issue.
With this change, we'll catch the error, do a simple console.log of the error message and exit with code 1, stopping `wunderctl up` immediately. This gives a simple and clear error message.

feat: improve error message when graphql introspection fails

---

packages/nextjs-testapp/.wundergraph/operations/ProtectedWeather.graphql
packages/nextjs-testapp/.wundergraph/wundergraph.config.ts
packages/nextjs-testapp/.wundergraph/wundergraph.server.ts
packages/nextjs-testapp/package.json
packages/nextjs-testapp/pages/auth-test.tsx
packages/nextjs/src/handlebar.template.ts
packages/nextjs/src/index.ts

This PR improves the nextjs package.
When no authentication provider is configured (cookie based auth), there's no need to fetch the user server-side as well as client-side, incl. re-fetching. This PR disables all user fetches in this case.

fix: don't (re-)fetch user server & client-side when authentication is disabled

---

cli/commands/generate.go
cli/commands/up.go
pkg/bundler/bundler.go
pkg/watcher/watcher.go

fix(watcher): make webhooks and fragments directory optional

---

.github/workflows/engine-ci.yaml
.gitignore
Makefile
pkg/s3uploadclient/helpers_test.go
pkg/s3uploadclient/s3uploadclient.go
pkg/s3uploadclient/s3uploadclient_test.go
pkg/s3uploadclient/testdata/testdata.go
scripts/minio-setup.sh

Bug description
------
- It's impossible to upload small files, like the ssh public key in my case. 
- It's impossible to upload files when the boundary prefix is followed by a double dash, space, tab, cr, nl, or end of input. 
In both these cases, EOF error returned within the response.  This is not correct, EOF should not be treated as an error in this case. 
There are a few issues with the existing implementation: 
```golang
contentTypeBuff := make([]byte, 512) // too much
_, err := part.Read(contentTypeBuff)
if err != nil {
// io.EOF error should be handled  
return nil, err
}
filetype := http.DetectContentType(contentTypeBuff) 
recycled := io.MultiReader(bytes.NewReader(contentTypeBuff), part)
```
```multipart.Part``` ```Read```  reads the body of a part, after its headers (!), and …

fix: s3 upload client

---

cli/commands/up.go
pkg/apihandler/apihandler.go
pkg/node/node.go

This allows you to run `wunderctl up` and never get logged out of the application during development.

feat: add dev mode so that cookie secrets stay static

---

pkg/apihandler/api.go
pkg/apihandler/apihandler.go
pkg/node/config.go

fix: use node url in graphiql apiUrl

---

packages/sdk/src/client/client.ts
pkg/apihandler/apihandler.go
pkg/apihandler/apihandler_test.go

If the request is multipart, don't log the body contents. This doesn't prevent logging the file in absolutely all cases (e.g. a PUT with the contents as the body), but it will omit the messages as long as the upload comes from the WunderGraph SDK. Added notes in both places to make sure they're kept in sync.
- [x ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

fix: avoid logging file contents during uploads (#201)

---

packages/sdk/src/definition/index.ts

fix(cache): dont print dev messages in prod mode

---

packages/sdk/src/definition/__snapshots__/index.test.ts.snap
packages/sdk/src/definition/graphql-introspection.ts

When we add a datasource that creates non-deterministic introspection results when the same data is in a different order. 
As a result, the introspection cache is always 'uniq' which causes infinite `watcher` calls .

fix: introspection, infinite loop in file changes

---

cli/commands/generate.go

The generated output files should all be written to a consistent `generated` directory.

fix: generate outfile directory should be consistent

---

cli/commands/add.go
cli/commands/generate.go
cli/commands/install-prisma-dependencies.go
cli/commands/mongodb.go
cli/commands/mysql.go
cli/commands/node.go
cli/commands/planetscale.go
cli/commands/postgres.go
cli/commands/publish.go
cli/commands/remove.go
cli/commands/root.go
cli/commands/server.go
cli/commands/sqlite.go
cli/commands/sqlserver.go
cli/commands/start.go
cli/commands/up.go

Some cmds, like `init` don't require the existence of the `.wundergraph` directory.
We always checked for this and failed if we didn't find it, which is wrong for init.

fix: make WunderGraphDir not mandatory for all cmds

---

packages/sdk/src/client/client.test.ts
packages/sdk/src/client/client.ts

`WunderGraphClient` should include `extraHeaders` passed into the constructor.
This should also fix the issue where `extraHeaders` passed into the `WunderGraphProvider` are ignored.

fix(sdk/client): include extra headers from constructor

---

Makefile

- Keep debug info, since it might be handy while developing
- Inject main.commit and main.date by spawing shell commands (they were
previously set to empty variables)

chore: improve wunderctl build from Makefile

---

Makefile
scripts/check-setup.sh
scripts/setup-dev.sh

- Install golangci-lint and gci via check-setup
- Add Makefile targets for format-go and golang-ci

chore: add formatting and ci tools for go

---

.github/workflows/packages-ci.yaml
packages/golang-client/src/index.ts

- fix: don't swallow gofmt errors, except gofmt being not present
- fix: go code generated from JSON mdel was missing a \n after slices

fix: incorrect go code generated from JSON models

---

cli/commands/node.go
cli/commands/start.go
pkg/httpidletimeout/httpidletimeout.go
pkg/httpidletimeout/httpidletimeout_test.go
pkg/node/node.go

- feat: add httpidletimeout package
- feat: implement idle timeout in wunderctl start

feat: allows node to sleep after an idle timeout

---

packages/sdk/src/configure/index.ts

If nothing is provided, default to allowing all origins

feat: make WunderGraphConfigApplicationConfig.cors optional

---

.github/workflows/engine-ci.yaml

1 minute seems a bit tight and is timing out from time to time.
Also, pin the golangci version to avoid having a new release trigger new
errors.

chore: increase go linter timeout in CI to 2 minutes

---

pkg/apihandler/apihandler.go
pkg/apihandler/apihandler_test.go

refactor the cache key to a constant to avoid repeating it

chore: rename X-Cache header to X-Wg-Cache

---

cli/commands/loadoperations.go
cli/commands/root.go
cli/commands/up.go

https://linear.app/wundergraph/issue/ENG-641/dont-enforce-pretty-logging-for-all-wunderctl-commands

fix: dont enforce prettyLogging for all commands

---

packages/sdk/src/definition/index.ts

This prevents the cache from getting in the way when the underlying file
changes. Since all the data to generate the introspection is local, we
don't need the cache to able to introspect without hitting the network.

fix: skip introspection cache when OpenAPI source is a file

---

cli/commands/generate.go
cli/commands/root.go
cli/commands/up.go
packages/wunderctl/src/binarypath.ts

Introduce a WUNDERCTL_BINARY_PATH environment variable. This can
be set either by the user or either by wunderctl itself. On startup,
wunderctl checks if the variable is unset and if it is, then it
sets it to its own path. The TS side now checks for this new variable
and when it's non-empty, it overrides the path to the wunderctl binary.

feat: ensure wunderctl always call the same copy when calling itself

---

packages/sdk/src/codegen/templates/typescript/client.template.ts

fix: set upload type when s3 is not configured

---

packages/sdk/src/codegen/templates/typescript/react.native.provider.template.ts
packages/sdk/src/codegen/templates/typescript/react.provider.template.ts
packages/sdk/src/codegen/templates/typescript/react.ts

Adds operation metadata to react provider's client instantiation.

fix: operation metadata in react provider

---

packages/sdk/src/v2openapi/__snapshots__/index.test.ts.snap
packages/sdk/src/v2openapi/index.ts
packages/sdk/src/v2openapi/testdata/users.json

OAS introspection was failing when references weren't object/array/enum, which meant that primitive schemas (e.g. `{ "type": "string" }`) were being interpreted as nested definitions.  Instead we can detect the primitive case and replace the field's schema with the schema from the reference.

fix(oas): use primitive schema references as the field schema

---

packages/sdk/src/codegen/templates/typescript/client.template.ts

The problem was that config is optional, but baseURL was required when adding a config, while baseURL has a default value. So when you add a customFetch for usage in nodejs, you also had to add baseURL which is incorrect.

fix: make baseURL optional

---

docs-website/src/pages/docs/features/automatic-content-revalidation-with-etags.md

Fix minor typo in documentation for word 'client-side'

docs: correct minor spelling typo

---

packages/create-wundergraph-app/src/helpers/download.ts
packages/create-wundergraph-app/src/helpers/examples.ts
packages/create-wundergraph-app/src/helpers/getRepoTags.ts
packages/create-wundergraph-app/src/helpers/getRepository.ts
packages/create-wundergraph-app/src/tests/index.test.ts

Downloading from the main branch prevents us from making breaking
changes, since the examples would stop working until the next SDK with
the breaking changes is released.
When using the wundegraph repository as the example source, first
retrieve the tags and use the latest tag starting with @wundergraph/sdk

feat(create-wundergraph-app): download latest tag instead of main

---

packages/sdk/package.json
packages/sdk/src/configure/index.ts
pnpm-lock.yaml

Interferes with logging, printing color sequences to JSON logs. Also,
we now have colors via --pretty-logging

fix: remove colors from configurePublishWunderGraphAPI()

---

pkg/apihandler/apihandler.go

end_session_endpoint is not a mandatory field, so it should print a
warning instead of an error. Also, add validation for the required
fields according to the spec.

fix: validate OpenID discovered configuration, warn when appropriate

---

docs-website/src/pages/docs/architecture/manage-api-dependencies-explicitly.md
docs-website/src/pages/docs/architecture/wundergraph-explained-in-one-sequence-diagram.md
docs-website/src/pages/docs/directives-reference/export-directive.md
docs-website/src/pages/docs/examples/cross-api-joins.md
docs-website/src/pages/docs/features/cross-api-joins-to-compose-apis.md
docs-website/src/pages/docs/use-cases/api-composition-and-integration.md
docs-website/src/pages/docs/use-cases/backend-for-frontend.md
examples/cross-api-joins/.wundergraph/wundergraph.config.ts
examples/publish-install-api/.wundergraph/wundergraph.config.ts
packages/sdk/src/definition/merge.test.ts
testapps/default/.wundergraph/wundergraph.config.ts
testapps/nextjs/.wundergraph/wundergraph.config.ts
testapps/vite/.wundergraph/wundergraph.config.ts

graphql-weather-api.herokuapp.com seems to have gone down permanently
after heroku removed their free tier

fix: replace graphql-weather-api.herokuapp.com with our own copy

---

packages/create-wundergraph-app/README.md
packages/create-wundergraph-app/package.json
packages/create-wundergraph-app/src/index.ts

fix: use the version from package.json for the --version command

---

packages/nextjs/package.json
pnpm-lock.yaml

object-hash was accidentally removed at some point, causing import
errors

fix: add missing dependency to our nextjs package

---

testapps/nextjs/package.json

We need to depend on the workspace, not on an specific version

fix: react-query dependency in testsapps/nextjs

---

cli/commands/root.go
pkg/files/files.go

This simplifies the build pipeline, so we don't need to pass this path explicitly for different use cases.
For example, when we allow the user to run a custom build script.

feat: find WG context based on config file

---

packages/sdk/src/testing/index.ts

fix: use 0.0.0.0 for test server

---

packages/wunderctl/README.md
packages/wunderctl/src/installer.ts

The user can set ` WG_COPY_BIN_PATH=~/.wundergraph/bin/wunderctl` to install the current wunderctl binary to a custom location. This is a convenient way to use the binary directly e.g. in docker, instead spawning a child process with `npm exec`, which also slows down cold starts by hundreds of milliseconds. Intentionally, we don't make the binary available to the user by default to not collide with different versions.

feat: copy wunderctl bin to wundergraph home dir

---

pkg/hooks/hooks.go
pkg/node/node.go
pkg/telemetry/client.go

After some testing, this is the sweet spot to archive better cold starts. Tested in FRA, fastest numbers after five trials:
Before: ~1.4s
After: ~1.08s

feat: improve backoff settings for cold starts

---

packages/create-wundergraph-app/package.json
packages/create-wundergraph-app/src/helpers/examples.ts
pnpm-lock.yaml

fix: filter only folders while listing examples

---

cli/commands/generate.go
cli/commands/node.go
cli/commands/server.go
cli/commands/up.go
pkg/config/config.go
pkg/datasources/database/engine.go
pkg/files/files.go
pkg/webhooks/webhooks.go

Use filepath.Join() instead of path.Join() to construct filesystem paths.

fix: incorrectly derived filesystem paths on Windows

---

docs-website/markdoc/tags.js
docs-website/src/components/Video.tsx

Usage in markdown
`{% video src="/videos/bunny.mp4" /%}`

feat: add support for videos in docs

---

packages/sdk/src/client/client.ts
packages/sdk/src/codegen/templates/typescript/client.template.ts

fix: use operationPath in client operation metadata

---

packages/react-query/src/types.ts

fix: add isSubscribed to return types

---

.github/workflows/packages-ci.yaml
.prettierignore

Tell prettier to ignore unknown extensions, and also exclude .html
files since we do not run those by prettier

chore: fix check for prettier formatted files in CI

---

packages/sdk/src/codegen/templates/typescript/index.ts
packages/sdk/src/server/plugins/functions.ts
pkg/loadoperations/loader.go

- Use filepath.Join() to manipulate file paths in the Go side
- In the typescript side, avoid path.join() to manipulate URL
- Fix file path to module import path conversion on Windows

fix: paths and uri composition on Windows when using nested directories for operations

---

docs-website/src/pages/docs/architecture/wundergraph-explained-in-one-sequence-diagram.md

Parameter value should be "EU", not "Europe"

docs: fix typo in "WunderGraph explained in one sequence diagram"

---

pkg/authentication/oidc.go

Instead of returning a 400, if we have a redirect_uri go to it but pass
a parameter with the error message. This allows the frontend to react
accordingly.

feat: when OIDC authentication is refused, redirect back with the error

---

packages/golang-client/src/index.ts
packages/nextjs/src/template.ts
packages/sdk/src/codegen/index.test.ts
packages/sdk/src/codegen/index.ts
packages/sdk/src/codegen/templates/markdown/authentication.ts
packages/sdk/src/codegen/templates/typescript/client.ts
packages/sdk/src/codegen/templates/typescript/forms.ts
packages/sdk/src/codegen/templates/typescript/hooks.ts
packages/sdk/src/codegen/templates/typescript/index.ts
packages/sdk/src/codegen/templates/typescript/internal.client.ts
packages/sdk/src/codegen/templates/typescript/internal.operations.client.ts
packages/sdk/src/codegen/templates/typescript/jsonschema.ts
packages/sdk/src/codegen/templates/typescript/linkbuilder.ts
packages/sdk/src/codegen/templates/typescript/operations.ts
packages/sdk/src/codegen/templates/typescript/react.ts
packages/sdk/src/codegen/templates/typescript/server.ts
packages/sdk/src/codegen/templates/typescript/testing.ts
packages/sdk/src/codegen/templates/typescript/web.client.ts
packages/sdk/src/codegen/templates/typescript/webhooks.ts
packages/sdk/src/configure/index.ts
packages/sdk/src/index.ts

Store ResolveApplicationConfig in a field in CodeGenerationConfig
rather than extending it. This allows us to safely hash ResolveApplicationConfig
without including the paths in CodeGenerationConfig.

fix: avoid feeding paths into applicationHash calculation

---

packages/create-wundergraph-app/src/helpers/examples.ts

fix: pass GH token in HTTTP call from getExamplesList()

---

packages/sdk/package.json
pnpm-lock.yaml

chore: bump wunderctl dependency to 0.131

---

pkg/datasources/database/engine.go

If Errors.Data is non-empty, print it

feat: provide more detailed error messages when introspecting databases

---

Makefile
packages/sdk/src/graphql/__snapshots__/schema.test.ts.snap
packages/sdk/src/graphql/schema.test.ts
packages/sdk/src/graphql/schema.ts
testapps/simple/.wundergraph/operations/Hello.graphql
testapps/simple/.wundergraph/wundergraph.server.ts

fix: graphql introspection with renamed query types

---

cli/helpers/process.go

Allows us to provide a better error message than crashing without an
explanation

fix: crash in ServerPortFromConfig when configuration is invalid

---

docs-website/src/pages/docs/cloud/custom-domains.md
pkg/apihandler/apitransport.go
pkg/hooks/hooks.go

Upload hooks don't have a client request

fix: don't require a clientRequest for hooks

---

packages/sdk/src/openapibuilder/__snapshots__/index.test.ts.snap
packages/sdk/src/openapibuilder/index.test.ts
packages/sdk/src/openapibuilder/index.ts
packages/sdk/src/openapibuilder/operations.ts

- fix: skip internal operations during OAS generation
- feat: annotate OAS operations with type and authentication requirements

feat: annotate OpenAPI spec with operation types and auth requirements

---

packages/sdk/src/codegen/templates/typescript/index.ts
testapps/openapi/geojson/.gitignore
testapps/openapi/geojson/.graphqlrc.yaml
testapps/openapi/geojson/.wundergraph/geojson.yaml
testapps/openapi/geojson/.wundergraph/operations/Location.graphql
testapps/openapi/geojson/.wundergraph/wundergraph.config.ts
testapps/openapi/geojson/.wundergraph/wundergraph.operations.ts
testapps/openapi/geojson/.wundergraph/wundergraph.server.ts
testapps/openapi/geojson/README.md
testapps/openapi/geojson/jest.config.js
testapps/openapi/geojson/package.json
testapps/openapi/geojson/test/index.test.ts
testapps/openapi/geojson/tsconfig.json

when trying to introspect an openapi datasource, 
with multi-dim array of numbers 
getting the following error:
```2023-03-07T00:26:14+02:00 FATAL: Couldn't configure your WunderNode: SyntaxError: Type expected. (6:14)
4 | features: {
5 | geometry: {
> 6 | coordinates: : : : number[],[],[],[],},
|              ^
7 | }[],},
8 | }
```
Error: 
```
coordinates: : : : number[],[],[],[]
```
expected to be 
```
coordinates: number[][][][]
```
a repo to reproduce error:
https://github.com/abdelhameedhamdy/geojson-api
a small fix added should fix the issue.
re-run introspection, error disappeared, schema generated as expected
coordinates: [[[[Int]]]]

fix: fixing multidimensional array schema in codegen (#731)Co-authored-by: abdelhameedalsayed <abdulhameed.azab@gmail.com>

---

pkg/apihandler/apihandler.go
pkg/node/node.go

gorilla/mux (the router we use) only runs middlewares when the path and method
match a registered handler. If we used a single router, we could circumvent
this limitation with a custom 404 handler, but since we use subrouters this
workaround doesn't work. Instead, wrap the whole mux.Router instance in the
CORS middleware, which will always run the middleware before mux.Router even
has a chance to dispatch the request. This causes all requests to include the CORS
header even if there's no matching handler.

feat: enable CORS headers for requests that result in 404/405

---

packages/sdk/src/configure/index.ts
testapps/default/test/index.test.ts

- Load only the .ts file with the response types instead of the whole
program
- Ignore non-fatal errors during schema generation
- Correctly set the schema in updateTypeScriptOperationsResponseSchemas()
before passing it to the OpenAPI builder (broken in #762)

fix: make TS operation response schema generation more forgiving

---

pkg/authentication/authentication.go
pkg/hooks/authentication.go
testapps/auth/.wundergraph/wundergraph.config.ts
testapps/auth/.wundergraph/wundergraph.server.ts
testapps/auth/test/index.test.ts

- Don't ignore error on postAuthentication with tokens
- Fix revalidation from Client when using token based authentication
- Call revalidation hook appropriately
- Unify error messages returned to callers from hooks that can deny auth
- Add tests for authentication hooks

fix: multiple fixes in authentication hooks

---

examples/apollo-federation/.env.example
examples/apollo-federation/README.md
examples/caching/.env.example
examples/caching/README.md
examples/hooks/.env.example
examples/hooks/README.md
examples/learn-wundergraph/.env.example
examples/learn-wundergraph/README.md
examples/nextjs-postgres-prisma/.env.example
examples/nextjs-postgres-prisma/README.md
examples/nextjs-postgres-user-filters/.env.example
examples/nextjs-postgres-user-filters/README.md
examples/nextjs-react-query/.env.example
examples/nextjs-react-query/README.md
examples/nextjs-typescript-functions/.env.example
examples/nextjs-typescript-functions/README.md
examples/nextjs/.env.example
examples/nextjs/README.md
examples/vite-swr/.env.example
examples/vite-swr/README.md
examples/webhooks/.env.example

Dummy secrets are now set by default in development mode

chore: delete example .env files for setting up dummy secrets

---

cli/commands/server.go
cli/commands/up.go
cli/helpers/server_runner.go

User needs a way to debug ts operations
PR adds `--inspect` param to the node process in case wunderctl was launched with `--debug` flag

feat: add ability to enable inspect for the server script runner

---

packages/nextjs/src/auth-middleware.ts
packages/nextjs/src/index.ts
packages/nextjs/src/types.ts
packages/nextjs/src/with-wundergraph.tsx

This PR adds improvements to the Next.js client.
- Exported useWunderGraphContext from package.
- New useAuthMiddleware helper hook, that allows you to inject tokens into the client.
- withWunderGraph now supports SWR middleware

feat: add auth middleware hook to nextjs client

---

docs-website/config/navigation.tsx
docs-website/src/pages/docs/cloud/errors.md

Documentation for Cloud build errors.
Build errors PR: https://github.com/wundergraph/cloud/pull/348/files

chore: add cloud error docs

---

docs-website/src/pages/docs/directives-reference/internal-operation-directive.md
docs-website/src/pages/docs/typescript-operations-reference/security.md
examples/learn-wundergraph/.wundergraph/operations/users/internal/getAdminUser.ts
examples/learn-wundergraph/.wundergraph/operations/weather/CountryWeather.ts
examples/learn-wundergraph/.wundergraph/operations/weather/internal/Country.graphql
examples/learn-wundergraph/.wundergraph/operations/weather/internal/Weather.graphql
packages/sdk/src/configure/index.ts
packages/sdk/src/graphql/operations.test.ts
packages/sdk/src/graphql/operations.ts
testapps/default/.wundergraph/operations/nested/InternalDirectoryWrapper.ts
testapps/default/.wundergraph/operations/nested/internal/Internal.graphql
testapps/default/test/index.test.ts

Operations are now marked as internal when under an `internal` folder.
WunderGraph will now automatically consider operations as internal when placed inside a directory name `internal`. This can be nested as well. All operations below are internal.
```
.wundergraph/
└── operations/
├── internal/
│   └── Weather.graphql
└── hello/
└── internal/
├── user.ts
└── more/
└── admin.ts
```

feat: mark operations as internal when inside internal folder

---

pkg/datasources/database/engine.go

Prisma was not loading variables from .env files. Consequently, `env(VAR_NAME)` will fail in a `schema.prisma`.

fix: allow prisma to load from .env

---

packages/svelte-query/README.md
packages/svelte-query/src/lib/createSvelteClient.ts
packages/svelte-query/tests/queryUtils.test.ts

Fixes an issue with svelte query's liveQuery which gets connected even when livequery config is set to false

fix: svelte-query livequery config

---

pkg/graphiql/graphiql.html
testapps/default/.wundergraph/wundergraph.config.ts

This fix includes user-defined headers in graphiql. Previously, we've omitted them in the custom GraphQL fetcher.

fix: include config headers in graphiql

---

pkg/apihandler/apihandler.go
pkg/graphiql/graphiql.html

Enable Subscriptions in GraphiQL 
Previously, we've only supported Queries & Mutations from the Playground.
Now you're able to use Subscriptions as well.

feat: enable subscriptions in graphiql

---

packages/testsuite/apps/basic/.wundergraph/operations/clientrequest/Header.graphql
packages/testsuite/apps/basic/.wundergraph/wundergraph.server.ts
packages/testsuite/apps/basic/index.test.ts
pkg/apihandler/apihandler.go

This fixes a bug where we first assign the client request to the request context and then override the context again, omitting the client request, which is then not properly injected into the transport, resulting in the client request missing in internal GraphQL requests to internally mounted/embedded GraphQL servers.

fix: don't override request context after assigning client request (#866

---

packages/sdk/src/configure/options.ts

The env we read for public node url is incorrect. This also broke vercel integration because we read a different env than we set.
Fixed a bug where the incorrect env was read for the public node url.

fix: incorrect env read for public node url

---

pkg/apihandler/apihandler.go
pkg/apihandler/internalapihandler.go

Copy prepared variables before merging user-defined variables to avoid corruption.
In very rare cases, it's possible that we're overriding the shared variables object in a way that will result in corruption. To avoid this, we're creating a copy first.

fix: variable corruption

---

docs-website/config/navigation.tsx
docs-website/src/pages/docs/guides/publish_generated-client-to-npm.md

A new guide that shows how to bundle the generated client for distribution to NPM

chore: add publish client guide

---

packages/testsuite/apps/openapi/.wundergraph/wundergraph.config.ts
packages/testsuite/apps/openapi/openapi.test.ts
pkg/apihandler/apihandler.go

Return 504 when an upstream produces a timeout

fix: detect all request timeouts correctly

---

packages/sdk/src/openapibuilder/index.test.ts
packages/sdk/src/openapibuilder/index.ts

- When rewriting type references, descend into object.anyOf
- When rewriting type references types that might have invalid names
in OAS (like anonymous types which use its representation) by hashing
their definition and generating a valid name.
ORM generates anonymous types that were not correctly handled by the OpenAPI generator
OpenAPI generation now works with the ORM

fix: handle anyOf and types with unrepresentable names in OAS

---

pkg/metrics/metrics.go
pkg/metrics/none.go
pkg/metrics/prometheus.go
pkg/node/node.go

Closing the metrics server gets rid of an error message that appears after a reload
during development

fix: close prometheus metrics when reloading the server

---

packages/sdk/package.json
packages/sdk/src/client/client.ts
packages/sdk/src/definition/graphql-introspection.test.ts
packages/sdk/src/server/operations-client.test.ts
packages/sdk/src/server/operations-client.ts
pnpm-lock.yaml

The cross-fetch package does not provide a web-streams compatible API required by the base client implementation. This cause `response.body.getReader is not a function` when starting a subscription with the operations client. We can provide different implementations for the Web and Server or use a web-stream compatible fetch on the server as well. I choose the second option.
This PR switched to `undici` as default fetch implementation on the server. It has support for Node.js 16+. As soon as Node.js 16 is out of maintenance, we can remove the package because, starting with Node.js 18, the exact fetch implementation is exposed as global.

fix: use Node.js fetch that supports web stream api

---

packages/sdk/package.json
pnpm-lock.yaml

chore: bump wunderctl dependency in SDK to 0.155.0

---

packages/testsuite/apps/orm/.wundergraph/operations/clientRequestContentLength.ts
packages/testsuite/apps/orm/.wundergraph/wundergraph.server.ts
packages/testsuite/apps/orm/orm.test.ts
pkg/pool/pool.go

Passes the right clientRequest to internal graphql requests

fix: use the right context.Context when reusing a resolve.Context in GetSharedFromRequest()

---

pkg/datasources/database/datasource.go
pkg/datasources/database/datasource_test.go

https://github.com/wundergraph/wundergraph/assets/47415099/16a0e792-047e-4fa1-935e-3f1cd57519e7
Add removeNullVariables directive for database data sources

feat: implement removeNullVariables for DB datasources

---

packages/sdk/package.json
pnpm-lock.yaml

chore: bump wunderctl dependency in SDK to 0.160.0

---

pkg/apihandler/apihandler.go
pkg/apihandler/apihandler_test.go
pkg/apihandler/graphql.go
pkg/apihandler/graphql_test.go

Otherwise we might pick a cached plan for a different operationName
Identified when determining operation types sent to GraphQL handler

fix: when caching a plan, take operationName into account

---

packages/sdk/src/testing/mock-server.test.ts
packages/sdk/src/testing/mock-server.ts
packages/sdk/src/testing/util.ts
packages/testsuite/apps/mock/.wundergraph/operations/CountryWeather.graphql
packages/testsuite/apps/mock/.wundergraph/wundergraph.config.ts
packages/testsuite/apps/mock/test/api-joins.test.ts

This PR provides an example of how to mock our `join` directive which issues multiple request to external API's. During this, I found an issue. We allow to read the request body multiple times when multiple mock handlers call `json`, `raw` or `text`.

fix(mock-library): ensure to read req body only once

---

README.md

very minor fix to point otel example link to that example instead of openapi example

chore: otel example link in readme

---

packages/sdk/src/logger/index.ts

fix: server logger missing cloud env bindings

---

packages/sdk/src/codegen/templates/typescript/jsonschema.template.ts

We extend the json schema type with custom attribute. We need to replicate this in the generated file.

fix: type error in generated jsonschema.ts file

---

packages/sdk/src/codegen/templates/typescript/jsonschema.template.ts

declare module instead of type in jsonschema.ts
Also Unless we set shamefully hoist, the module is not detected with pnpm. So we just ts-ignore it in that case. Other package managers have no issue. This is done to bypass pnpm with testapps.

fix: jsonschema template

---

packages/sdk/package.json
pnpm-lock.yaml

Since prettier is used for formatting during code generation, we
need it as a dependency of the SDK

fix: add prettier as a direct SDK dependency

---

pkg/scriptrunner/scriptrunner.go

The 16K default can be too low when introspecting big files, raise it
to 8MB

fix: increase line buffer size when running a script from wunderctl

---

pkg/apihandler/graphql.go

Use relative URLs to find the GraphQL endpoint, since both the endpoint and the playground
have to be served from the same host.

feat: make GraphQL playground available in more scenarios without additional configuration

---

pkg/apihandler/apihandler.go

The call to flusher.Flush() causes the ResponseWriter to write a header
with a 200 HTTP code, preventing us from correctly returning 500 in case
of errors.

fix: remove duplicate WriteHeader calls

---

cli/commands/up.go
pkg/apihandler/apihandler_test.go
pkg/cui/cui.go

Even if we're exiting, we need to call keyboard.Close() to restore
the terminal state

fix: don't interfere with terminal after running wunderctl up

---

pkg/authentication/authentication.go
pkg/authentication/oidc.go

Neither token nor cookie based providers work with sign in with apple via Auth0. The reason is that apple provides the email_verified field as a string. This breaks the parser which expects a boolean value. I fixed the token based flow here.

fix: string email_verified fields from sign in with apple

---

pkg/apihandler/apitransport.go

Allow the duration to format itself, which will print appropriate units
depending on how long it is

fix: show correct upstream request duration

---

pkg/apihandler/apihandler.go
pkg/authentication/authentication.go
pkg/authentication/config.go
pkg/authentication/oauth2.go

Since the redirect_uri used after authentication will be an absolute URL
in most cases, we can take advantage of this to autodetect the protocol. The
result is that most users won't ever need to touch this setting, unless the
manually perform the logging in using host-relative URLs.

feat: improve protocol detection when determining callback URLs from auth providers

---

pkg/apihandler/apihandler.go
pkg/apihandler/authentication.go
pkg/apihandler/internalapihandler.go
pkg/authentication/authentication.go
pkg/authentication/oauth2.go
pkg/hooks/authentication.go

feat: allow revalidate hook to alter the user object, then save it back

---

docs-website/src/pages/docs/apis/apollo-federation/index.md
docs-website/src/pages/docs/databases/prisma.md

- correct typo in index.md, section apollo-federation.
- correct typo in prisma.md, section databases.
Simply just maintaining docs credibility and ensuring correct spelling and grammar in the documentation.

docs: fix "therefor" typos 

---

packages/sdk/src/codegen/generateoperations.ts
packages/sdk/src/codegen/index.ts
packages/sdk/src/graphql/operations.ts
packages/sdk/src/postman/builder.ts
packages/sdk/src/v2openapi/__snapshots__/index.test.ts.snap
packages/sdk/src/v2openapi/index.ts
testapps/default/.wundergraph/operations/federated/TopProducts.graphql

This PR implements feature of respecting the OAS Schema's **default** properties when generating respectful GraphQL operations (during introspection). 
The GQL Specification Nodes contain the default values (for Queries/Mutations)  and they are now taken into consideration and reflected within the gql operations generated during Wundergraph introspection.
This PR fixes #1322.
If the (OAS/...) Schema Definitions specify operations with query parameters having **default** values specified within the respective Schema definitions, these default values will be reflected as defaults when generating GraphQL Operations during the introspection phase.

feat: add default values support for generated operations

---

packages/sdk/src/server/plugins/omnigraphOAS.ts
packages/sdk/src/server/plugins/omnigraphSOAP.ts
packages/sdk/src/server/server.ts
packages/sdk/src/server/types.ts

fix: add globalfetch configuration option to server

---

.github/goreleaser/.goreleaser-darwin.yml

`brew install wundergraph/wundergraph/wunderctl` is broken, and returns the following error:
```
==> Fetching wundergraph/wundergraph/wunderctl
==> Downloading https://github.com/wundergraph/wundergraph/releases/download/0.176.2/wunderctl_0.176.2_Da
curl: (22) The requested URL returned error: 404
Error: wunderctl: Failed to download resource "wunderctl"
Download failed: https://github.com/wundergraph/wundergraph/releases/download/0.176.2/wunderctl_0.176.2_Darwin_arm64.tar.gz
```
This is because the string template for the URL to the asset in `.github/goreleaser/.goreleaser-darwin.yml:127` is missing a 'v' after '/releases/downloads/' in the link.
Link from github releases: 
```
https://github.com/wundergraph/wundergraph/releases/download/v0.176.2/wunderctl_0.176.2_Darwin_arm64.tar.gz …
```

fix(brew): update homebrew asset link to include v

---

pkg/apihandler/apihandler.go

fix: fixed issue where input validation errors would not return correct content type header

---

docs-website/src/pages/docs/examples/nuxt.md
docs-website/src/pages/docs/supported-frontend-frameworks/nuxt.md
examples/nuxt/plugins/vue-query.ts

This is a DX improvement when developing - we can avoid loading the entire barrel file at `#app` by using the new granular imports merged in https://github.com/nuxt/nuxt/pull/23951.

fix: import nuxt composables from #imports

---

packages/sdk/src/configure/codegeneration.ts

fix: fixed issue where fields in operation generator would be added as subscription root type

---

packages/sdk/src/client/client.ts
packages/swr/src/hooks.ts
pkg/authentication/oauth2.go
testapps/nextjs/pages/authentication.tsx

This adds support to forward query params from the client to the auth provider, e.g. the `/authorize?organization=wundergraph` to dynamically pre-select an org when starting the login process.

feat: allow forwarding query params on login

---

packages/sdk/src/client/client.ts
packages/sdk/src/client/types.ts
pkg/authentication/authentication.go
pkg/authentication/oidc.go

feat: allow forwarding of params from client logout

---

examples/nextjs-app-dir/src/app/actions.ts

Noticed an erroneous import for "data" from "autoprefixer" which is not used by the function. This frequently happens with intellisense auto-imports.

remove erroneous data import from autoprefixer
